### ISSUE TITLE
rvierdiiev - Stream doesn't have ability to rescue native token

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-nounsdao-judging#14]
rvierdiiev

medium

# Stream doesn't have ability to rescue native token

## Summary
Stream doesn't have ability to rescue native token
## Vulnerability Detail
Stream.rescueERC20 function allows payer to rescue tokens that he sent by mistake.
But it doesn't have function to rescue native tokens that are sent by mistake.
## Impact
Payer can't withdraw native tokens that are sent by mistake.
## Code Snippet
https://github.com/sherlock-audit/2022-11-nounsdao/blob/main/src/Stream.sol#L268-L272
## Tool used

Manual Review

## Recommendation
Add ability to withdraw native token from Stream.

Duplicate of #47

**Comment by rvierdiyev** [comment]
Escalate for 1 USDC
This is clear duplicate of [47](https://github.com/sherlock-audit/2022-11-nounsdao-judging/issues/47) and not of [28](https://github.com/sherlock-audit/2022-11-nounsdao-judging/issues/28).
Here i am also talking that you have rescueERC20 function, but don't have rescueEth function.

**Comment by hrishibhat** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
