### ISSUE TITLE
rvierdiiev - StreamFactory.createStream with predictedStreamAddress always uses nonce == 0

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-nounsdao-judging#16]
rvierdiiev

high

# StreamFactory.createStream with predictedStreamAddress always uses nonce == 0

## Summary
StreamFactory.createStream with predictedStreamAddress always uses nonce == 0. That means that it will be not possible to create second Stream with same params and check predictedStreamAddress.
## Vulnerability Detail
StreamFactory has createStream function which takes predictedStreamAddress param to check if address of created Stream is same as predictedStreamAddress.
https://github.com/sherlock-audit/2022-11-nounsdao/blob/main/src/StreamFactory.sol#L156-L167
```solidity
    function createStream(
        address recipient,
        uint256 tokenAmount,
        address tokenAddress,
        uint256 startTime,
        uint256 stopTime,
        address predictedStreamAddress
    ) external returns (address stream) {
        stream =
            createStream(msg.sender, recipient, tokenAmount, tokenAddress, startTime, stopTime, 0);
        if (stream != predictedStreamAddress) revert UnexpectedStreamAddress();
    }
```
As you can see this function then calls  `createStream(msg.sender, recipient, tokenAmount, tokenAddress, startTime, stopTime, 0)` and provides 0 as nonce param. Here nonce is used to make it possible to create Stream with same params.
That means that it will be not possible to use this function if you want to create same Stream contract(with same params) again, as because of same nonce the address will be the same and it will be not possible to create contract that already exists.

From docs we can see that this function is going to be used to create Streams from dao.
> First the user (in our case the DAO's web UI) calls `predictStreamAddress` to get the future stream contract address.
Then a proposal can be composed with the following two transactions:
>1. `StreamFactory.createStream(...)`, where the new stream's address should match `predictStreamAddress`
>2. `Payer.sendOrRegisterDebt(...)`, where the payment recipient is the address from `predictStreamAddress`

Scenario.
1.Stream for 100$ from January to February is created using createStream function with predictedStreamAddress param.
2.There is a need to create one more such Stream contract in such way.
3.The call to createStream with predictedStreamAddress param reverts because contract with such address is already created.
## Impact
Not possible to create Stream with same params using createStream function with predictedStreamAddress param
## Code Snippet
https://github.com/sherlock-audit/2022-11-nounsdao/blob/main/src/StreamFactory.sol#L156-L167
## Tool used

Manual Review

## Recommendation
Add one more param to method to provide nonce.

**Comment by eladmallel** [comment]
Fix PR: https://github.com/nounsDAO/streamer/pull/11
