### ISSUE TITLE
ctf_sec - Any payment token can be used when calling StreamFactory.sol#createStream

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-nounsdao-judging#20]
ctf_sec

medium

# Any payment token can be used when calling StreamFactory.sol#createStream

## Summary

Any payment token can be used when calling StreamFactory.sol

## Vulnerability Detail

According to the on-chain context and the description of the doc: 

the project is planning to support USDC and WETH as payment token,

https://app.sherlock.xyz/audits/contests/27

```solidity
DEPLOYMENT: mainnet
ERC20: USDC and WETH
```

However, such a check is not enforced when creating the stream, caller of the contract can basically use any payment token (a fee-on-transfer token or ERC777 token that allow re-entrancy) to set up the stream, the project are not intended to support these token, but the user can still set up stream using these token.

```solidity
function createStream(
    address payer,
    address recipient,
    uint256 tokenAmount,
    address tokenAddress,
    uint256 startTime,
    uint256 stopTime,
    uint8 nonce
) public returns (address stream) {
```

## Impact

the caller of the create stream can set up a malicious token that support infinite minting as the payment token to rug the payment recipient, or the caller can just use the token other than USDC or WETH as the payment that the project does not intend to support.

## Code Snippet

https://github.com/sherlock-audit/2022-11-nounsdao/blob/main/src/StreamFactory.sol#L168-L214

## Tool used

Manual Review

## Recommendation

We recommend the project whitelist a list of the token supported and verify if the payment token is in the whitelist instead of letting user inject whatever token they want as the payment token.

The project can begin by whitelisting the USDC and WETH token that the project is intended to support.

Duplicate of #45

**Comment by ctf-sec** [comment]
Escalate for 1 USDC.

The core issue is not using fee-on-transfer / ERC777 token, the core issue is that the lack of sanity check for token address and the contract allows token other than WETH / USDC to be used as mentioned in the impact section.

> the caller of the create stream can set up a malicious token that support infinite minting as the payment token to rug the payment recipient, or the caller can just use the token other than USDC or WETH as the payment that the project does not intend to support.

I think this should be at least a duplicate of https://github.com/sherlock-audit/2022-11-nounsdao-judging/issues/65

**Comment by hrishibhat** [comment]
Escalation rejected

Input sanity check for token addresses which the protocol does not support can be considered a low severity.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Input sanity check for token addresses which the protocol does not support can be considered a low severity. 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
