### ISSUE TITLE
rvierdiiev - Not possible to create stream that pays less than 1 token per second

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-nounsdao-judging#5]
rvierdiiev

medium

# Not possible to create stream that pays less than 1 token per second

## Summary
Not possible to create stream that pays less than 1 token per second
## Vulnerability Detail
StreamFactory doesn't allow to create a Stream that pays less than 1 token per second. However it's possible that such situation will occur.

StreamFactory.createStream validates input params and has such check `if (tokenAmount < stopTime - startTime) revert TokenAmountLessThanDuration();`. This check disallow to create Stream that will pay less than 1 token per second. But it's possible that such payment possibility will be needed.

USDC has 6 decimals that means that 1$ is 1_000_000 tokens.
One day has 86400 seconds.
1_000_000 / 86400 = 11.57. This states that if you want to pay 1 token per second than you will spend 1$ in 11.57 days.

So if you want to have Stream that pays 1$ in 15 days(or 2$ in 30 days, or 100$ in 1500 days and so on) you will not be able to do that.
But as for me it's possible to have a contract that pays 1$ in 15 days for smth. 
## Impact
Not possible to create stream that pays less than 1 token per second
## Code Snippet
https://github.com/sherlock-audit/2022-11-nounsdao/blob/main/src/StreamFactory.sol#L200
## Tool used

Manual Review

## Recommendation
Remove that constraint.

Duplicate of #63

**Comment by eladmallel** [comment]
Fix PR: https://github.com/nounsDAO/streamer/pull/12
